### ISSUE TITLE
Break data down per day rather than showing all data points

### ISSUE THREAD

**Issue by thomasdenney** [BandToThePole/MobileApp#4]
This can be done in the various view model classes.

See [this function](https://github.com/BandToThePole/WebSite/blob/master/static/js/core.js#L47) that is used on the website to achieve the same thing.

@Alex-Rice an alternative option is to move this onto the server and then modify the API so that it only serves one data point per day for distance and calories. Heart rate data should still be more granular though.

**Comment by Alex-Rice** [comment]
Will do this on server

**Comment by thomasdenney** [comment]
@Alex-Rice Great, I'll move this issue to the website repo.
